### ISSUE TITLE
Ничего не работает

### ISSUE THREAD

**Issue by loveuloveme** [VanjaRo/Music_controller#1]
Запускаю, а ничего не работает.
**Проблема кроется где-то здесь:**
![image](https://user-images.githubusercontent.com/54083203/103694997-e16e3f00-4fac-11eb-8a6e-ffa36b51d587.png)

**Comment by loveuloveme** [comment]
- 

- [ ] @

- [ ] 

1. 

> __

**Comment by VanjaRo** [comment]
\_(*_*)_/, я не уверен, что оно должно сразу брать и работать без установки фреймворка)
